### PR TITLE
core: arduino: add ShiftIn/ShiftOut implementation 

### LINKED ISSUE #345: `shiftIn` + `shiftOut` not implemented
## Describe the bug

The [`shiftIn`](https://docs.arduino.cc/language-reference/en/functions/advanced-io/shiftIn/) and [`shiftOut`](https://docs.arduino.cc/language-reference/en/functions/advanced-io/shiftOut/) functions are part of the standardized Arduino core API:

It is expected that every core will implement these functions.

🐛 These functions have not been implemented in this core, which causes compilation of any sketch program referencing them to fail.

## Target board + cli verbose compilation output

```text
FQBN: arduino-dev:zephyr:unoq
Using board 'unoq' from platform in folder: /home/per/Arduino/hardware/arduino-dev/zephyr
Using core 'arduino' from platform in folder: /home/per/Arduino/hardware/arduino-dev/zephyr

Detecting libraries used...
/home/per/.arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/arm-zephyr-eabi-g++ -g -Os -std=gnu++17 -c -D_PICOLIBC_CTYPE_SMALL=1 -w -imacros/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx/llext-edk/include/zephyr/include/generated/zephyr/autoconf.h -imacros/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx/llext-edk/include/zephyr/include/zephyr/toolchain/zephyr_stdint.h @/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx/cxxflags.txt -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-unwind-tables -fno-use-cxa-atexit -lstdc++ -lsupc++ -lnosys -nostdlib -lstdc++ -lsupc++ -lm -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-unwind-tables -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -w -x c++ -E -CC -DARDUINO=10607 -DARDUINO_UNO_Q -DARDUINO_ARCH_ZEPHYR -DARDUINO_ARCH_ZEPHYR -DARDUINO_LIBRARY_DISCOVERY_PHASE=1 -I/home/per/Arduino/hardware/arduino-dev/zephyr/cores/arduino -I/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx -I/home/per/Arduino/hardware/arduino-dev/zephyr/cores/arduino/api/deprecated -I/home/per/Arduino/hardware/arduino-dev/zephyr/cores/arduino/api/deprecated-avr-comp -iprefix/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx @/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx/includes.txt /home/per/.cache/arduino/sketches/C2E1E84F507BEC59F3E0FE043B27681B/sketch/sketch_feb16a.ino.cpp -o /dev/null
Generating function prototypes...
/home/per/.arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/arm-zephyr-eabi-g++ -g -Os -std=gnu++17 -c -D_PICOLIBC_CTYPE_SMALL=1 -w -imacros/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx/llext-edk/include/zephyr/include/generated/zephyr/autoconf.h -imacros/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx/llext-edk/include/zephyr/include/zephyr/toolchain/zephyr_stdint.h @/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx/cxxflags.txt -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-unwind-tables -fno-use-cxa-atexit -lstdc++ -lsupc++ -lnosys -nostdlib -lstdc++ -lsupc++ -lm -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-unwind-tables -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -w -x c++ -E -CC -DARDUINO=10607 -DARDUINO_UNO_Q -DARDUINO_ARCH_ZEPHYR -DARDUINO_ARCH_ZEPHYR -DARDUINO_LIBRARY_DISCOVERY_PHASE=1 -I/home/per/Arduino/hardware/arduino-dev/zephyr/cores/arduino -I/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx -I/home/per/Arduino/hardware/arduino-dev/zephyr/cores/arduino/api/deprecated -I/home/per/Arduino/hardware/arduino-dev/zephyr/cores/arduino/api/deprecated-avr-comp -iprefix/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx @/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx/includes.txt /home/per/.cache/arduino/sketches/C2E1E84F507BEC59F3E0FE043B27681B/sketch/sketch_feb16a.ino.cpp -o /tmp/3377184631/sketch_merged.cpp
/home/per/.arduino15/packages/builtin/tools/ctags/5.8-arduino11/ctags -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives /tmp/3377184631/sketch_merged.cpp

Compiling sketch...
/home/per/.arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/arm-zephyr-eabi-g++ -g -Os -std=gnu++17 -c -D_PICOLIBC_CTYPE_SMALL=1 -w -imacros/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx/llext-edk/include/zephyr/include/generated/zephyr/autoconf.h -imacros/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx/llext-edk/include/zephyr/include/zephyr/toolchain/zephyr_stdint.h @/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx/cxxflags.txt -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-unwind-tables -fno-use-cxa-atexit -lstdc++ -lsupc++ -lnosys -nostdlib -lstdc++ -lsupc++ -lm -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-unwind-tables -MMD -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -DARDUINO=10607 -DARDUINO_UNO_Q -DARDUINO_ARCH_ZEPHYR -DARDUINO_ARCH_ZEPHYR -DARDUINO_LIBRARY_DISCOVERY_PHASE=0 -I/home/per/Arduino/hardware/arduino-dev/zephyr/cores/arduino -I/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx -I/home/per/Arduino/hardware/arduino-dev/zephyr/cores/arduino/api/deprecated -I/home/per/Arduino/hardware/arduino-dev/zephyr/cores/arduino/api/deprecated-avr-comp -iprefix/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx @/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx/includes.txt /home/per/.cache/arduino/sketches/C2E1E84F507BEC59F3E0FE043B27681B/sketch/sketch_feb16a.ino.cpp -o /home/per/.cache/arduino/sketches/C2E1E84F507BEC59F3E0FE043B27681B/sketch/sketch_feb16a.ino.cpp.o
Compiling libraries...
Compiling core...
Using previously compiled file: /home/per/.cache/arduino/sketches/C2E1E84F507BEC59F3E0FE043B27681B/core/analogReference.cpp.o
Using precompiled core: /home/per/.cache/arduino/cores/cd06985031a4388a327205bbbe5be235/core.a
/home/per/.arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld: Linking everything together...
/home/per/.arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/arm-zephyr-eabi-g++ -L/home/per/.cache/arduino/sketches/C2E1E84F507BEC59F3E0FE043B27681B -L/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx -Wl,--gc-sections -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -std=gnu++17 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-unwind-tables -fno-use-cxa-atexit -lstdc++ -lsupc++ -lnosys -nostdlib --specs=nano.specs --specs=nosys.specs /home/per/.cache/arduino/sketches/C2E1E84F507BEC59F3E0FE043B27681B/sketch/sketch_feb16a.ino.cpp.o /home/per/.cache/arduino/sketches/C2E1E84F507BEC59F3E0FE043B27681B/core/analogReference.cpp.o -Wl,--start-group /home/per/.cache/arduino/sketches/C2E1E84F507BEC59F3E0FE043B27681B/../../cores/cd06985031a4388a327205bbbe5be235/core.a -lstdc++ -lsupc++ -lm -Wl,--end-group -e main -T/home/per/Arduino/hardware/arduino-dev/zephyr/variants/arduino_uno_q_stm32u585xx/syms-dynamic.ld -T/home/per/Arduino/hardware/arduino-dev/zephyr/variants/_ldscripts/memory-check.ld -T/home/per/Arduino/hardware/arduino-dev/zephyr/variants/_ldscripts/build-static.ld -o /home/per/.cache/arduino/sketches/C2E1E84F507BEC59F3E0FE043B27681B/sketch_feb16a.ino_check.tmp
/home/per/.cache/arduino/sketches/C2E1E84F507BEC59F3E0FE043B27681B/sketch/sketch_feb16a.ino.cpp.o: in function `setup':
/tmp/.arduinoIDE-unsaved2026116-88512-1ow9ssf.xfr/sketch_feb16a/sketch_feb16a.ino:3: undefined reference to `shiftOut'
/home/per/.arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld: /tmp/.arduinoIDE-unsaved2026116-88512-1ow9ssf.xfr/sketch_feb16a/sketch_feb16a.ino:3: undefined reference to `shiftIn'
collect2: error: ld returned 1 exit status
exit status 1

Compilation error: exit status 1
```

## Mandatory: attach the sketch

```cpp
void setup() {
  shiftIn(2, 3, MSBFIRST);
  shiftOut(4, 5, LSBFIRST, 42);
}
void loop() {}
```

## Additional context

Reproduced using 87421b48c6d4cbd1d5f29085f327306395e0adfe

---

Originally reported at https://forum.arduino.cc/t/74hc595-with-arduino-uno-q/1424622

### PR DESCRIPTION
**Pull request by KurtE**
resolves: #345 

Note: I simply copied in the MBED version of this.  The APIS were already contained within the header files.

Verified that the sketch within the issue built.
Modified it to verify that worked at all:
```
void setup() {
  // put your setup code here, to run once:
  pinMode(2, INPUT);
  pinMode(3, OUTPUT);
  pinMode(4, OUTPUT);
  pinMode(5, OUTPUT);
  //shiftIn(2, 3, MSBFIRST);
  //shiftOut(4, 5, LSBFIRST, 42);
  pinMode(LED_BUILTIN, OUTPUT);

}

uint8_t loop_count = 0;
void loop() {
  // put your main code here, to run repeatedly:
  loop_count++;
  digitalWrite(LED_BUILTIN, loop_count & 1);
  shiftOut(4, 5, LSBFIRST, loop_count);
  delay(1);
}

```
Built and ran on UnoQ with current sources as of this morning.
image

It has the same possible issue as the MBED version in that the faster the processor, the narrower the pulses are:
image
I know in the case of Teensy 4.x boards, they put in possible delays, but that could be looked at later if needed.

### CODE REVIEW

**Review by pennam — APPROVED** [review]

**Review by pillo79 — CHANGES_REQUESTED** [review]
Thanks @KurtE, but we would like to avoid including LGPL licensed code directly in the main core. Even though the final license of any Arduino build is always LGPL, the "core" itself is Apache2 and this would be the first incompatible bit.

The implementation of `shiftIn`/`shiftOut` should be rewritten from scratch to make this viable for inclusion. Would you like to give it a try? 🤗

File: cores/arduino/wiring_shift.cpp [hunk 1]
```diff
@@ -0,0 +1,50 @@
+/*
+ * Copyright (c) Arduino s.r.l. and/or its affiliated companies
```
Comment (pillo79) [inline cores/arduino/wiring_shift.cpp]: Use your name (or alias, if you prefer)... it's your work! 😉

**Review by pillo79 — COMMENTED** [review]
Thank you for the code and test! I suggest one trivial fix, but LGTM! 🙂

File: cores/arduino/wiring_shift.cpp (hunk 1 above)
Comment (KurtE) [reply cores/arduino/wiring_shift.cpp]: Could do, but is there any way to mark it as Copyright, everyone who has ever shifted in or out a byte ;)

Comment (KurtE) [reply cores/arduino/wiring_shift.cpp]: But pushed up the change

Comment (KurtE) [reply cores/arduino/wiring_shift.cpp]: However now the test for licenses fail...

File: cores/arduino/wiring_shift.cpp [hunk 2]
```diff
@@ -0,0 +1,50 @@
+/*
+ * Copyright (c) KurtE
```
Comment (pillo79) [inline cores/arduino/wiring_shift.cpp]: It seems the name is too short for it to be reliably detected by scancode. Black magic.
Can you please try this alternative? (the tag is case sensitive)
 
```suggestion
 * SPDX-FileCopyrightText: Copyright (c) KurtE
```

(or try adding the year?).

File: cores/arduino/wiring_shift.cpp [hunk 3]
```diff
@@ -0,0 +1,49 @@
+/*
+ * SPDX-FileCopyrightText: Copyright (c) KurtE
```
Comment (pillo79) [inline cores/arduino/wiring_shift.cpp]: Did a few tests locally.  It appears if you add `SPDX-FileCopyrightText:` then you do NOT have to add `Copyright`. But it does require the year. So confusing! 🤷‍♂️ 

I have tested this works:
```
 * Copyright (c) 2026 KurtE
```

(there is also ` * SPDX-FileCopyrightText: 2026 KurtE `, but it isn't used anywhere else in the repo, so I'd prefer the above one).
Sorry about this flurry of changes!

Comment (KurtE) [reply cores/arduino/wiring_shift.cpp]: Updated, fingers crossed

Comment (KurtE) [reply cores/arduino/wiring_shift.cpp]: I believe it is resolved.

**Review by pillo79 — APPROVED** [review]
Thanks for the ping, yes, no issues from me!
