### PR TITLE
UNOQ: implement proper "wait for app" mode

### LINKED ISSUE #347: UNO Q - Current sources - running a sketch, then running APP, power off and on - Faults
Today I synced up to the latest sources and built both on PC and on Q.

I burned bootloader on Q with latest.  I ran my Weather 2 app.
Up on github in: https://github.com/KurtE/Arduino_UNO_Q

Stopped the APP.

I then went to PC and uploaded a sketch, in this case test of Events, which I uploaded IDE2 with todays build.

Went back to APP Lab reran Weather2.

Turned off power to Q, turned back on and it faults: (data on Serial D0, D1)
```
*** Booting Zephyr OS build v4.2.0-40-g7d8afd96730f ***
Invalid sketch header
[00:00:29.299,000] <err> os: ***** HARD FAULT *****
[00:00:29.304,000] <err> os:   Debug event
[00:00:29.309,000] <err> os: r0/a1:  0x00000000  r1/a2:  0x00000000  r2/a3:  0x40014800
[00:00:29.318,000] <err> os: r3/a4:  0x00002341 r12/ip:  0x00003e80 r14/lr:  0x08005507
[00:00:29.327,000] <err> os:  xpsr:  0x49000000
[00:00:29.332,000] <err> os: s[ 0]:  0x183dd1ba  s[ 1]:  0x0801884c  s[ 2]:  0x08019b54  s[ 3]:  0x438293f5
[00:00:29.342,000] <err> os: s[ 4]:  0x08018080  s[ 5]:  0x00007b0d  s[ 6]:  0x54acdc08  s[ 7]:  0x00000000
[00:00:29.353,000] <err> os: s[ 8]:  0x00000000  s[ 9]:  0x00000000  s[10]:  0x00000000  s[11]:  0x00000000
[00:00:29.363,000] <err> os: s[12]:  0x00000000  s[13]:  0x00000000  s[14]:  0x00000000  s[15]:  0x00000000
[00:00:29.373,000] <err> os: fpscr:  0x00000000
[00:00:29.379,000] <err> os: Faulting instruction address (r15/pc): 0x0800550c
[00:00:29.387,000] <err> os: >>> ZEPHYR FATAL ERROR 0: CPU exception on CPU 0
[00:00:29.394,000] <err> os: Current thread: 0x20000568 (main)
[00:00:29.401,000] <err> os: Halting system
```

Note: it has been happening for a while now.  Did not see that with last released version.

### PR DESCRIPTION
**Pull request by facchinm**
The current implementation of "Flash Mode=RAM" was meant to syncronize the startup of the microcontroller with an application launched by AppLab.
However, it has a bunch of limitiations which make it basically useless for bigger projects.

Replace it with another step of (gpio-based) syncronization, so AppLab can safely decide when to unlock the boot. 
* Depends on the corresponding PR in arduino-app-cli 
* Requires a rebuild+repackage of zephyr-sketch-tool

@lucarin91 @pillo79

### CODE REVIEW

File: loader/main.c [hunk 1]
```diff
@@ -202,15 +192,13 @@ static int loader(const struct shell *sh) {
...
-			if (sketch_hdr->ver == 0x1 && sketch_hdr->magic == 0x2341) {
-				// Found valid data, use it for booting
-				base_addr = (uintptr_t)ram_firmware;
-				*ram_start = 0;
-				sketch_valid = true;
+		if (sketch_hdr->flags & SKETCH_FLAG_WAIT_FOR_APP) {
+			// wait for another pin toggle
+			while (gpio_pin_get_dt(&spec) != 0) {
+				k_sleep(K_MSEC(10));
+			}
```
Comment (lucarin91) [inline loader/main.c]: Maybe we should make this more robust by setting a max length of the LOW state, e.g., 200ms?

File: variants/arduino_uno_q_stm32u585xx/flash_sketch.cfg
Comment (lucarin91) [inline variants/arduino_uno_q_stm32u585xx/flash_sketch.cfg:1]: you can also remove the `variants/arduino_uno_q_stm32u585xx/flash_sketch_ram.cfg` file

**Review by lucarin91 — APPROVED** [review]
Tested with this `arduino-app-cli` [PR](https://github.com/arduino/arduino-app-cli/pull/254) and it works correctly. Given that you are also removing the flash-to-ram mode, we need to ensure our PR is released in prod before this one.

**Review by pennam — APPROVED** [review]
