### PR TITLE
build: Fix linker errors when using CPP features.

### LINKED ISSUE #302: UNDEFINED Ref to __throw_bad_alloc(),  _Unwind_GetTextRelBase, _Unwind_VRS_Get, __gnu_unwind_frame etc and Hard fault
**Describe the bug**
Getting compile errors for multiple defs of __throw_bad_alloc and several other undefined errors. 

**Target board + cli verbose compilation output**
Tried on Arduino Q and Arduino Giga
```
loading library from d:\Users\Merli\Documents\Arduino\libraries\Arduino-EasyTransfer-master: invalid library: no header files foundloading library from d:\Users\Merli\Documents\Arduino\libraries\ArduinoCore-API-master: invalid library: no header files foundloading library from d:\Users\Merli\Documents\Arduino\libraries\FastAhrs: invalid library: no header files foundloading library from d:\Users\Merli\Documents\Arduino\libraries\Lidar-Lite-v3-3d-Scanner: invalid library: no header files foundloading library from d:\Users\Merli\Documents\Arduino\libraries\M5Stack: invalid library: no header files foundloading library from d:\Users\Merli\Documents\Arduino\libraries\esp32-camera-master: invalid library: no header files found
FQBN: arduino:zephyr:unoq
Using board 'unoq' from platform in folder: C:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0
Using core 'arduino' from platform in folder: C:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0

Detecting libraries used...
C:\Users\Merli\AppData\Local\Arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8/bin/arm-zephyr-eabi-g++ -g -Os -std=gnu++17 -c -w -imacrosC:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\variants\arduino_uno_q_stm32u585xx/llext-edk/include/zephyr/include/generated/zephyr/autoconf.h -imacrosC:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\variants\arduino_uno_q_stm32u585xx/llext-edk/include/zephyr/include/zephyr/toolchain/zephyr_stdint.h @C:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\variants\arduino_uno_q_stm32u585xx/cxxflags.txt -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-unwind-tables -fno-use-cxa-atexit -lstdc++ -lsupc++ -lnosys -nostdlib -lstdc++ -lsupc++ -fdata-sections -ffunction-sections -fno-unwind-tables -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -w -x c++ -E -CC -DARDUINO=10607 -DARDUINO_UNO_Q -DARDUINO_ARCH_ZEPHYR -DARDUINO_ARCH_ZEPHYR -DARDUINO_LIBRARY_DISCOVERY_PHASE=1 -IC:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\cores\arduino -IC:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\variants\arduino_uno_q_stm32u585xx -IC:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\cores\arduino/api/deprecated -IC:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\cores\arduino/api/deprecated-avr-comp -iprefixC:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\variants\arduino_uno_q_stm32u585xx @C:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\variants\arduino_uno_q_stm32u585xx/includes.txt C:\Users\Merli\AppData\Local\arduino\sketches\CA6F3CDAE87FD181817C16D0B0304EC1\sketch\sketch_dec19c.ino.cpp -o nul
Generating function prototypes...
C:\Users\Merli\AppData\Local\Arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8/bin/arm-zephyr-eabi-g++ -g -Os -std=gnu++17 -c -w -imacrosC:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\variants\arduino_uno_q_stm32u585xx/llext-edk/include/zephyr/include/generated/zephyr/autoconf.h -imacrosC:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\variants\arduino_uno_q_stm32u585xx/llext-edk/include/zephyr/include/zephyr/toolchain/zephyr_stdint.h @C:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\variants\arduino_uno_q_stm32u585xx/cxxflags.txt -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-unwind-tables -fno-use-cxa-atexit -lstdc++ -lsupc++ -lnosys -nostdlib -lstdc++ -lsupc++ -fdata-sections -ffunction-sections -fno-unwind-tables -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -w -x c++ -E -CC -DARDUINO=10607 -DARDUINO_UNO_Q -DARDUINO_ARCH_ZEPHYR -DARDUINO_ARCH_ZEPHYR -DARDUINO_LIBRARY_DISCOVERY_PHASE=1 -IC:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\cores\arduino -IC:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\variants\arduino_uno_q_stm32u585xx -IC:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\cores\arduino/api/deprecated -IC:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\cores\arduino/api/deprecated-avr-comp -iprefixC:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\variants\arduino_uno_q_stm32u585xx @C:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\variants\arduino_uno_q_stm32u585xx/includes.txt C:\Users\Merli\AppData\Local\arduino\sketches\CA6F3CDAE87FD181817C16D0B0304EC1\sketch\sketch_dec19c.ino.cpp -o C:\Users\Merli\AppData\Local\Temp\447230873\sketch_merged.cpp
C:\Users\Merli\AppData\Local\Arduino15\packages\builtin\tools\ctags\5.8-arduino11/ctags -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives C:\Users\Merli\AppData\Local\Temp\447230873\sketch_merged.cpp

Compiling sketch...
"C:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\zephyr\\tools\\arm-zephyr-eabi\\0.16.8/bin/arm-zephyr-eabi-g++" -g -Os -std=gnu++17 -c -w "-imacrosC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\variants\\arduino_uno_q_stm32u585xx/llext-edk/include/zephyr/include/generated/zephyr/autoconf.h" "-imacrosC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\variants\\arduino_uno_q_stm32u585xx/llext-edk/include/zephyr/include/zephyr/toolchain/zephyr_stdint.h" "@C:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\variants\\arduino_uno_q_stm32u585xx/cxxflags.txt" -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-unwind-tables -fno-use-cxa-atexit -lstdc++ -lsupc++ -lnosys -nostdlib -lstdc++ -lsupc++ -fdata-sections -ffunction-sections -fno-unwind-tables -MMD -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -DARDUINO=10607 -DARDUINO_UNO_Q -DARDUINO_ARCH_ZEPHYR -DARDUINO_ARCH_ZEPHYR -DARDUINO_LIBRARY_DISCOVERY_PHASE=0 "-IC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\cores\\arduino" "-IC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\variants\\arduino_uno_q_stm32u585xx" "-IC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\cores\\arduino/api/deprecated" "-IC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\cores\\arduino/api/deprecated-avr-comp" "-iprefixC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\variants\\arduino_uno_q_stm32u585xx" "@C:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\variants\\arduino_uno_q_stm32u585xx/includes.txt" "C:\\Users\\Merli\\AppData\\Local\\arduino\\sketches\\CA6F3CDAE87FD181817C16D0B0304EC1\\sketch\\sketch_dec19c.ino.cpp" -o "C:\\Users\\Merli\\AppData\\Local\\arduino\\sketches\\CA6F3CDAE87FD181817C16D0B0304EC1\\sketch\\sketch_dec19c.ino.cpp.o"
Compiling libraries...
Compiling core...
"C:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\zephyr\\tools\\arm-zephyr-eabi\\0.16.8/bin/arm-zephyr-eabi-g++" -g -Os -std=gnu++17 -c -w "-imacrosC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\variants\\arduino_uno_q_stm32u585xx/llext-edk/include/zephyr/include/generated/zephyr/autoconf.h" "-imacrosC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\variants\\arduino_uno_q_stm32u585xx/llext-edk/include/zephyr/include/zephyr/toolchain/zephyr_stdint.h" "@C:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\variants\\arduino_uno_q_stm32u585xx/cxxflags.txt" -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-unwind-tables -fno-use-cxa-atexit -lstdc++ -lsupc++ -lnosys -nostdlib -lstdc++ -lsupc++ -fdata-sections -ffunction-sections -fno-unwind-tables -MMD -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -DARDUINO=10607 -DARDUINO_UNO_Q -DARDUINO_ARCH_ZEPHYR -DARDUINO_ARCH_ZEPHYR -DARDUINO_LIBRARY_DISCOVERY_PHASE=0 "-IC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\cores\\arduino" "-IC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\variants\\arduino_uno_q_stm32u585xx" "-IC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\cores\\arduino/api/deprecated" "-IC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\cores\\arduino/api/deprecated-avr-comp" "-iprefixC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\variants\\arduino_uno_q_stm32u585xx" "@C:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\variants\\arduino_uno_q_stm32u585xx/includes.txt" "C:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\variants\\arduino_uno_q_stm32u585xx\\analogReference.cpp" -o "C:\\Users\\Merli\\AppData\\Local\\arduino\\sketches\\CA6F3CDAE87FD181817C16D0B0304EC1\\core\\analogReference.cpp.o"
Using precompiled core: C:\Users\Merli\AppData\Local\arduino\cores\301537ad63e630cbd99f5dd769e0d364\core.a
Linking everything together...
"C:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\zephyr\\tools\\arm-zephyr-eabi\\0.16.8/bin/arm-zephyr-eabi-g++" "-LC:\\Users\\Merli\\AppData\\Local\\arduino\\sketches\\CA6F3CDAE87FD181817C16D0B0304EC1" "-LC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\variants\\arduino_uno_q_stm32u585xx" -Wl,--gc-sections -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -std=gnu++17 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-unwind-tables -fno-use-cxa-atexit -lstdc++ -lsupc++ -lnosys -nostdlib --specs=picolibc.specs --specs=nosys.specs "C:\\Users\\Merli\\AppData\\Local\\arduino\\sketches\\CA6F3CDAE87FD181817C16D0B0304EC1\\sketch\\sketch_dec19c.ino.cpp.o" "C:\\Users\\Merli\\AppData\\Local\\arduino\\sketches\\CA6F3CDAE87FD181817C16D0B0304EC1\\core\\analogReference.cpp.o" -Wl,--start-group "C:\\Users\\Merli\\AppData\\Local\\arduino\\sketches\\CA6F3CDAE87FD181817C16D0B0304EC1/..\\..\\cores\\301537ad63e630cbd99f5dd769e0d364\\core.a" -lstdc++ -lsupc++ -Wl,--end-group -e main "-TC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0\\variants\\arduino_uno_q_stm32u585xx/syms-dynamic.ld" "-TC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0/variants/_ldscripts/memory-check.ld" "-TC:\\Users\\Merli\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\zephyr\\0.52.0/variants/_ldscripts/build-static.ld" -o "C:\\Users\\Merli\\AppData\\Local\\arduino\\sketches\\CA6F3CDAE87FD181817C16D0B0304EC1/sketch_dec19c.ino_check.tmp"
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(functexcept.o): in function `std::__throw_bad_alloc()':
functexcept.cc:(.text.unlikely._ZSt17__throw_bad_allocv+0x0): multiple definition of `std::__throw_bad_alloc()'; C:\Users\Merli\AppData\Local\arduino\sketches\CA6F3CDAE87FD181817C16D0B0304EC1/..\..\cores\301537ad63e630cbd99f5dd769e0d364\core.a(abi.cpp.o):C:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\cores\arduino/abi.cpp:14: first defined here
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(functexcept.o): in function `std::__throw_length_error(char const*)':
functexcept.cc:(.text.unlikely._ZSt20__throw_length_errorPKc+0x0): multiple definition of `std::__throw_length_error(char const*)'; C:\Users\Merli\AppData\Local\arduino\sketches\CA6F3CDAE87FD181817C16D0B0304EC1/..\..\cores\301537ad63e630cbd99f5dd769e0d364\core.a(abi.cpp.o):C:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.52.0\cores\arduino/abi.cpp:11: first defined here
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(functexcept.o):(.ARM.exidx.text.unlikely._ZSt28__throw_bad_array_new_lengthv+0x0): undefined reference to `__aeabi_unwind_cpp_pr1'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_arm.o):(.ARM.exidx.text.__cxa_type_match+0x0): undefined reference to `__aeabi_unwind_cpp_pr0'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_personality.o):(.ARM.exidx.text._ZL28read_encoded_value_with_basehjPKhPj+0x0): undefined reference to `__aeabi_unwind_cpp_pr0'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_personality.o): in function `base_of_encoded_value(unsigned char, _Unwind_Context*)':
eh_personality.cc:(.text._ZL21base_of_encoded_valuehP15_Unwind_Context+0x2e): undefined reference to `_Unwind_GetTextRelBase'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: eh_personality.cc:(.text._ZL21base_of_encoded_valuehP15_Unwind_Context+0x36): undefined reference to `_Unwind_GetDataRelBase'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: eh_personality.cc:(.text._ZL21base_of_encoded_valuehP15_Unwind_Context+0x3e): undefined reference to `_Unwind_GetRegionStart'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_personality.o):(.ARM.exidx.text._ZL21base_of_encoded_valuehP15_Unwind_Context+0x0): undefined reference to `__aeabi_unwind_cpp_pr1'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_personality.o):(.ARM.exidx.text._ZL18read_encoded_valueP15_Unwind_ContexthPKhPj+0x0): undefined reference to `__aeabi_unwind_cpp_pr0'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_personality.o): in function `parse_lsda_header(_Unwind_Context*, unsigned char const*, lsda_header_info*)':
eh_personality.cc:(.text._ZL17parse_lsda_headerP15_Unwind_ContextPKhP16lsda_header_info+0xa): undefined reference to `_Unwind_GetRegionStart'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_personality.o):(.ARM.exidx.text._ZL17parse_lsda_headerP15_Unwind_ContextPKhP16lsda_header_info+0x0): undefined reference to `__aeabi_unwind_cpp_pr0'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_personality.o): in function `_Unwind_GetGR':
eh_personality.cc:(.text._Unwind_GetGR+0xc): undefined reference to `_Unwind_VRS_Get'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_personality.o):(.ARM.exidx.text._Unwind_GetGR+0x0): undefined reference to `__aeabi_unwind_cpp_pr0'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_personality.o): in function `__gxx_personality_v0':
eh_personality.cc:(.text.__gxx_personality_v0+0x28): undefined reference to `__gnu_unwind_frame'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: eh_personality.cc:(.text.__gxx_personality_v0+0x54): undefined reference to `_Unwind_VRS_Set'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: eh_personality.cc:(.text.__gxx_personality_v0+0x88): undefined reference to `_Unwind_VRS_Set'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: eh_personality.cc:(.text.__gxx_personality_v0+0x9a): undefined reference to `_Unwind_VRS_Set'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: eh_personality.cc:(.text.__gxx_personality_v0+0xbc): undefined reference to `_Unwind_VRS_Set'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: eh_personality.cc:(.text.__gxx_personality_v0+0xe6): undefined reference to `_Unwind_GetLanguageSpecificData'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_terminate.o):(.ARM.exidx.text._ZN10__cxxabiv112__unexpectedEPFvvE+0x0): undefined reference to `__aeabi_unwind_cpp_pr1'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_terminate.o):(.ARM.exidx.text._ZSt10unexpectedv+0x0): undefined reference to `__aeabi_unwind_cpp_pr1'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_throw.o):(.ARM.exidx.text._ZL23__gxx_exception_cleanup19_Unwind_Reason_CodeP21_Unwind_Control_Block+0x0): undefined reference to `__aeabi_unwind_cpp_pr0'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_throw.o): in function `__cxa_throw':
eh_throw.cc:(.text.__cxa_throw+0x26): undefined reference to `_Unwind_RaiseException'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_throw.o):(.ARM.exidx.text.__cxa_throw+0x0): undefined reference to `__aeabi_unwind_cpp_pr0'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(si_class_type_info.o):(.ARM.exidx.text._ZNK10__cxxabiv120__si_class_type_info11__do_upcastEPKNS_17__class_type_infoEPKvRNS1_15__upcast_resultE+0x0): undefined reference to `__aeabi_unwind_cpp_pr0'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(class_type_info.o):(.ARM.exidx.text._ZNK10__cxxabiv117__class_type_info11__do_upcastEPKS0_PPv+0x0): undefined reference to `__aeabi_unwind_cpp_pr0'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:\users\merli\appdata\local\arduino15\packages\zephyr\tools\arm-zephyr-eabi\0.16.8\bin\../lib/gcc/../../picolibc/arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++.a(eh_catch.o): in function `__cxa_begin_catch':
eh_catch.cc:(.text.__cxa_begin_catch+0x4c): undefined reference to `_Unwind_Complete'
collect2.exe: error: ld returned 1 exit status
exit status 1

Compilation error: exit status 1
```

**Mandatory: attach the sketch**

[sketch_dec19c-251219a.zip](https://github.com/user-attachments/files/24259997/sketch_dec19c-251219a.zip)

**Additional context**
Note getting same errors on the Giga as well.  Tested the sketch on a Teensy 4.1 and ran without issue.  Typical output:
```
0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 
0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 
0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 
0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 
0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 
0.50 0.50 0.50 0.50 0.50 0.12 0.27 0.27 0.27 0.82 
0.50 0.50 0.50 0.50 0.50 0.50 0.27 0.50 0.50 0.50 
0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.27 0.50 0.50 
0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.27 0.50 
0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.50 0.27 
```

### PR DESCRIPTION
**Pull request by iabdalkader**
Fixes #302

The sketch below fails to link with a loader compiled with/without `--debug`, with static or dynamic link mode. The errors are multiple definitions of `std::__throw_bad_alloc()` etc... It seems the specs we're using (picolibc.specs) links libraries compiled with exceptions enabled, which provide those functions. Note that the discard doesn't help here, probably because it comes at a later stage after symbol resolution.

If you simply remove the stubs provided in `abi.cpp`, the static link mode works, but dynamic fails with errors like the following:

```
libstdc++.a(eh_arm.o):(.ARM.exidx.text.__cxa_type_match+0x0): undefined reference to `__aeabi_unwind_cpp_pr0'
```
I think the above proves that exceptions are still enabled, since it's looking for some unwind symbol.

This patch switches to `nano.specs`, which disables C++ exceptions and provides the needed stubs. Additionally, long-call veneers are added for all libc functions that could be called by the LLEXT extension. This fixes isses issues with precompiled toolchain libraries that emit R_ARM_THM_JUMP24 / R_ARM_THM_CALL relocations for the export libc functions.

I've tested this by building with a loader built with/without `--debug` and with static/dynamic link modes in each case and all seem to work fine.

```C
#include <memory>
#include <string>
#include <vector>

std::shared_ptr<int> test;
std::string myString;
std::vector<int> myVector;

static void custom_deleter(int *fd) {
    delete fd;
}

void setup() {
    test = nullptr;
    test = std::shared_ptr<int>(nullptr, custom_deleter);

    // Test std::string
    myString = "Hello Arduino";
    myString += " Zephyr!";

    // Test std::vector
    myVector.push_back(1);
    myVector.push_back(2);
    myVector.push_back(3);

    for (auto& val : myVector) {
        val *= 2;
    }
}

void loop() {
}
```

### CODE REVIEW

**Comment by pillo79** [comment]
Ran a [full set of build tests](https://github.com/pillo79/ArduinoCore-zephyr/actions/runs/21034569443#summary-60480697953) using the CI I'm working on, and it indeed fixes the C++ errors on all targets :partying_face: 
However, the run found one tiny new issue only on the **`unoq:static`** build:

```
  /home/runner/.arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld: /home/runner/.arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard/libm_nano.a(lib_a-w_sqrt.o): in function `sqrt':
  w_sqrt.c:(.text.sqrt+0x3c): undefined reference to `__errno'
  collect2: error: ld returned 1 exit status
```
(full log [here](https://github.com/pillo79/ArduinoCore-zephyr/actions/runs/21034569443/job/60479910032#step:6:508), not much extra detail though)

I suspect the issue is core-wide, but the unoq is the only target where I compiled that function. TBH, not sure how `libm` and `errno` interact at all and why it was working before the PR! :eyes: :man_shrugging:

**Review by pillo79 — APPROVED** [review]
Latest push fixed it, thanks!

**Comment by iabdalkader** [comment]
Yeah, I see the issue now. It seems it fails when libstdc++ calls those functions, not when they're called directly from sketch.

**Comment by KurtE** [comment]
>Note, I'd be willing to give the suggested fix (in the linked issue) a try, but I honestly don't know if it's worth. I don't see why we need to bother with dynamic mode at all, unless I'm missing something, we could just use static mode for everything.

It is my impression that with Dynamic mode, you can for example update the bootloader and in theory your sketch will continue to be useable and Static implies you must update the program as well. 

But I am guessing you probably understand this stuff a lot better than I do.

File: cores/arduino/llext_wrappers.c [hunk 1]
```diff
@@ -0,0 +1,166 @@
+/*
+ * Copyright (c) 2026 Arduino SA
```
Comment (pillo79) [inline cores/arduino/llext_wrappers.c]: We should be using this new copyright line from now on:

```suggestion
 * Copyright 2026 ARDUINO SRL (https://www.arduino.cc)
```

Note that Zephyr does not want the link so on upstream patches we need to drop that 🤷

File: loader/llext_exports.c [hunk 2]
```diff
@@ -12,69 +12,78 @@
...
-EXPORT_SYMBOL(strchr);
-EXPORT_SYMBOL(strcat);
-EXPORT_SYMBOL(memmove);
+/*
+ * Libc functions are exported with a __real_ prefix so that the sketch
+ * core can provide long-call trampolines under the original names.
+ * This avoids R_ARM_THM_JUMP24 / R_ARM_THM_CALL relocations that would
+ * fail when the LLEXT is loaded in a different memory region (>16 MB away).
+ */
+#define EXPORT_LIBC_SYM(name) EXPORT_SYMBOL_NAMED(name, __real_##name)
```
Comment (pillo79) [inline loader/llext_exports.c:21]: Please group symbols that use this either in a separate file or at the beginning/end of this one, to make it easier to keep track of what requires this wrapper.

**Review by pillo79 — COMMENTED** [review]
Thanks, LGTM, minor nits below.

**Comment by mjs513** [comment]
@iabdalkader 

Not going to want to hear this - I applied the patch and took a look at the changed files and stiil getting that error on the uno_q
```
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++_nano.a(functexcept.o): in function `std::__throw_bad_alloc()':
functexcept.cc:(.text.unlikely._ZSt17__throw_bad_allocv+0x0): multiple definition of `std::__throw_bad_alloc()'; C:\Users\Merli\AppData\Local\arduino\sketches\E00C18A620415558739259E231674CAA/core\core.a(abi.cpp.o):C:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.53.0\cores\arduino/abi.cpp:14: first defined here
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libstdc++_nano.a(functexcept.o): in function `std::__throw_length_error(char const*)':
functexcept.cc:(.text.unlikely._ZSt20__throw_length_errorPKc+0x0): multiple definition of `std::__throw_length_error(char const*)'; C:\Users\Merli\AppData\Local\arduino\sketches\E00C18A620415558739259E231674CAA/core\core.a(abi.cpp.o):C:\Users\Merli\AppData\Local\Arduino15\packages\arduino\hardware\zephyr\0.53.0\cores\arduino/abi.cpp:11: first defined here
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib/thumb/v8-m.main+fp/hard\libm_nano.a(lib_a-w_exp.o): in function `exp':
w_exp.c:(.text.exp+0x3a): undefined reference to `__errno'
c:/users/merli/appdata/local/arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: w_exp.c:(.text.exp+0x66): undefined reference to `__errno'
collect2.exe: error: ld returned 1 exit status
exit status 1
```
